name: Test

on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - elixir: 1.17.x
            otp: 27
          - elixir: 1.16.x
            otp: 26
          - elixir: 1.15.x
            otp: 26
          - elixir: 1.14.x
            otp: 26
          - elixir: 1.13.x
            otp: 25

    services:
      postgres:
        image: postgres:12
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Elixir
      id: beam
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Check formatting
      run: mix format --check-formatted

    - name: Setup EventStore test databases
      run: |
        MIX_ENV=test mix event_store.setup
        MIX_ENV=jsonb mix event_store.setup

    - name: Compile
      run: mix compile --warnings-as-errors

    - name: Run tests
      run: mix test.all

    - name: Retrieve Dialyzer PLT cache
      uses: actions/cache@v3
      id: plt-cache
      with:
        path: priv/plts
        key: ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-plts-${{ hashFiles('**/mix.lock') }}

    - name: Create Dialyzer PLTs
      if: steps.plt-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p priv/plts
        mix dialyzer --plt

    - name: Run Dialyzer
      run: mix dialyzer --no-check
